### ISSUE TITLE
In README.md, under Planned Features, "repetition" is mispelled

### ISSUE THREAD

**Issue by mnorelli** [sbrks/flashcards#3]
Sam, I really appreciated your well-written README, especially the first section where you put this project into context.  Well done.  Just happened to notice this one thing.

**Comment by mnorelli** [comment]
Another spelling thing.  In the answer to "what is an API?", the answer has a trailing "a".

**Comment by mnorelli** [comment]
And maybe another answer edit?  
`true || false` evaluates to `true`.  You show `*false` for this answer.

**Comment by sbrks** [comment]
Ahhh yes, thanks for catching those. Fixed!
