### ISSUE TITLE
Flashcards: Question/Answer

### ISSUE THREAD

**Issue by LadyPi** [sbrks/flashcards#6]
When clicking on the 'New Card' button you get a question but you also get the answer. It would be nice to either have it on one card or at least make it so that the 'Answer Card' only shows when you click on 'Answer'. 

Great job! I can't wait to play this again. Wonderful way to learn!

**Comment by sbrks** [comment]
Thanks Vanessa! Great feedback. I've hidden the answer on "New Question" click.
